#include "internalshadermanager.h"
#include "internalshaders.h"

/* Vertex shader */
VECHAR p_ShaderPlanetVertex[] = ""
"varying vec3 lightDir;\r\n"
"varying vec3 viewDir;\r\n"
"varying vec2 texCoord;\r\n"
""
"varying vec4 position;\r\n"
"varying vec4 color0;\r\n"
"varying vec4 color1;\r\n"
"varying vec3 v3Direction;\r\n"
""
"attribute vec4 "VE_SHADERPARAM_TANGENTS";\r\n"
"attribute vec3 "VE_SHADERPARAM_BINORMALS";\r\n"
""
"uniform vec4 "VE_SHADERPARAM_CAMERAPOS";\r\n"
""
"const float PI = 3.14159265358979323846264;\r\n"
""
"const float fKrESun = 0.0000025 * 10;\r\n"
"const float fKmESun = 0.00015 * 10;\r\n"
"const vec3 v3InvWaveLength = vec3(1.0 / pow(0.650, 4), 1.0 / pow(0.570, 4), 1.0 / pow(0.475, 4));\r\n"
""
"const float fCameraHeight  = 3.0;\r\n"
"const float fCameraHeight2 = pow(fCameraHeight, 2.0);\r\n"
""
"const float fOuterRadius  = 1.025;\r\n"
"const float fOuterRadius2 = pow(fOuterRadius, 2);\r\n"
"const float fInnerRadius  = 1.0;\r\n"
"const float fInnerRadius2 = pow(fInnerRadius, 2);\r\n"
""
"const float fKr4PI = fKrESun * 4 * PI;\r\n"
"const float fKm4PI = fKmESun * 4 * PI;\r\n"
""
"const float fScale = 1.0 / (fOuterRadius - fInnerRadius);\r\n"
"const float fScaleDepth = 1.0125;\r\n"
"const float fScaleOverScaleDepth = 1.0 / fScaleDepth;\r\n"
""
"const float fSamples  = 2.0;\r\n"
"const int   nSamples  = 2;\r\n"
""
"float scale(float fCos)\r\n"
"{\r\n"
"	float x = 1.0 - fCos;\r\n"
"	return fScaleDepth * exp(-0.00287 + x*(0.459 + x*(3.83 + x*(-6.80 + x*5.25))));\r\n"
"}\r\n"
""
"void main()"
"{"
""
"  gl_Position = gl_ModelViewProjectionMatrix * gl_Vertex;\r\n"
"  texCoord = gl_MultiTexCoord0.xy;\r\n"
""
"  vec3 vertexPos = vec3(gl_ModelViewMatrix * gl_Vertex);\r\n"
"  vec3 vVertex = vec3(gl_ModelViewMatrix * gl_Vertex);\r\n"
"  vec3 tmpVec = gl_LightSource[0].position.xyz - vVertex;\r\n"
""
"  vec3 n = normalize(gl_NormalMatrix * gl_Normal);\r\n"
"  vec3 t = normalize(gl_NormalMatrix * "VE_SHADERPARAM_TANGENTS".xyz);\r\n"
"  vec3 b = normalize("VE_SHADERPARAM_BINORMALS");\r\n"
""
"  lightDir = vec3(dot(tmpVec, t), dot(tmpVec, b), dot(tmpVec, n));\r\n"
""
"  vec3 v3Pos = gl_Position.xyz;\r\n"
"  vec3 v3CameraPos = "VE_SHADERPARAM_CAMERAPOS".xyz;\r\n"
"  vec3 v3Ray = v3Pos - v3CameraPos;\r\n"
"  float fFar = length(v3Ray);\r\n"
"  v3Ray /= fFar;\r\n"
""
"  float B = 2.0 * dot(v3CameraPos, v3Ray);\r\n"
"  float C = fCameraHeight2 - fOuterRadius2;\r\n"
"  float fDet = max(0.0, B*B - 4.0 * C);\r\n"
"  float fNear = 0.5 * (-B - sqrt(fDet));\r\n"
""
"  vec3 v3Start = v3CameraPos + v3Ray * fNear;\r\n"
"  fFar -= fNear;\r\n"
""
"  float fSampleLength = fFar / fSamples;\r\n"
"  float fScaledLength = fSampleLength * fScale;\r\n"
"  vec3 v3SampleRay = v3Ray * fSampleLength;\r\n"
"  vec3 v3SamplePoint = v3Start + (v3SampleRay * 0.5);\r\n"
""
"  float fHeight = length(v3SamplePoint);\r\n"
"  float fStartAngle = dot(v3Ray, v3Start) / fHeight;\r\n"
"  float fStartDepth = exp(fScaleOverScaleDepth * (fInnerRadius - fHeight));\r\n"
"  float fStartOffset = fStartDepth * scale(fStartAngle);\r\n"
""
"  vec3 v3FrontColor = float3(0.0, 0.0, 0.0);\r\n"
"  for(int i=0; i<nSamples; i++)\r\n"
"  {\r\n"
"    float fHeight = length(v3SamplePoint);\r\n"
"    float fDepth = exp(fScaleOverScaleDepth * (fOuterRadius-fHeight));\r\n"
"    float fLightAngle = dot(lightDir, v3SamplePoint) / fHeight;\r\n"
"    float fCameraAngle = dot(v3Ray, v3SamplePoint) / fHeight;\r\n"
"    float fScatter = (fStartOffset + fDepth * (scale(fLightAngle) - scale(fCameraAngle)));\r\n"
"    vec3 v3Attenuate = exp(-fScatter * (v3InvWaveLength * fKr4PI + fKm4PI));\r\n"
"    v3FrontColor += v3Attenuate * (fDepth * fScaledLength);\r\n"
"    v3SamplePoint += v3SampleRay;\r\n"
"  }\r\n"
""
"  vec3 test=v3FrontColor*fKmESun;\r\n"
"  color1 = float4(test, 1);\r\n"
"  test = v3FrontColor * v3InvWaveLength * fKrESun;\r\n"
"  color0 = float4(test, 1);\r\n"
""
"  position = gl_ModelViewProjectionMatrix * gl_Vertex;\r\n"
"  v3Direction = v3CameraPos - v3Pos;\r\n"
""
"  tmpVec   = -vVertex;\r\n"
"  viewDir  = normalize(vec3(dot(tmpVec, t), dot(tmpVec, b), dot(tmpVec, n)));\r\n"
"}";

/* Fragment shader */
VECHAR p_ShaderPlanetFragment[] = ""
"uniform sampler2D "VE_SHADERPARAM_MAPDIFFUSE";\r\n"
"uniform sampler2D "VE_SHADERPARAM_MAPNORMALS";\r\n"
""
"varying vec3 lightDir;\r\n"
"varying vec3 viewDir;\r\n"
"varying vec2 texCoord;\r\n"
""
"varying vec4 position;\r\n"
"varying vec4 color0;\r\n"
"varying vec4 color1;\r\n"
"varying vec3 v3Direction;\r\n"
""
"const float g =-0.90;\r\n"
"const float g2 = 0.81;\r\n"
"const float fExposure = 2;\r\n"
""
"void main()"
"{"
"  vec3  nn    = 2.0*texture2D ( "VE_SHADERPARAM_MAPNORMALS", texCoord).xyz - vec3 ( 1.0 );\r\n"
"  float alpha = 0.6;\r\n"
"  float y     = gl_FragCoord.y * 0.5;\r\n"
//"  if ( alpha < 1.0 )\r\n"
//"    if ( fract ( y ) < 0.5 )\r\n"
//"      discard;\r\n"
""
//"  gl_FragData [0] = vec4 ( nn, 1.0 );\r\n"
//"  gl_FragData [1] = vec4 ( texture2D ( "VE_SHADERPARAM_MAPDIFFUSE", texCoord ).rgb, alpha );\r\n"
""
"  vec4 baseColor = texture2D("VE_SHADERPARAM_MAPDIFFUSE", texCoord);\r\n"
"  vec3 normal = normalize(texture2D("VE_SHADERPARAM_MAPNORMALS", texCoord).rgb * 2.0 - 1.0);\r\n"
""
"  vec4 ambientColor = gl_LightSource[0].ambient * baseColor;\r\n"
""
"  float diffuse = clamp(dot(lightDir, normal), 0.0, 1.0);\r\n"
"  vec4 diffuseColor = gl_LightSource[0].diffuse * baseColor * diffuse;\r\n;"
""
"  float baseShininess = texture2D("VE_SHADERPARAM_MAPNORMALS", texCoord).a;\r\n"
"  float specular = pow(clamp(dot(reflect(-lightDir, normal), viewDir), 0.0, 1.0), baseShininess);\r\n"
"  vec4 specularColor = gl_LightSource[0].specular * specular;\r\n"
""
"  vec4 surfaceColor = ambientColor + diffuseColor + specularColor;\r\n"
""
"  vec4 atmosphereColor = vec4(1.0, 1.0, 1.0, 0.5);\r\n"
""
"  float k = 0.0; //dot(normalize(lightDir), normal);\r\n"
""
//"  gl_FragColor = surfaceColor;\r\n"
//"  gl_FragColor = mix(surfaceColor, atmosphereColor, k); "
//"  gl_FragColor = mix(surfaceColor, atmosphereColor, k);\r\n"
""
"  float3 ldir = normalize(v3Direction);\r\n"
"  float fCos=dot(lightDir,ldir);\r\n"
"  float fRayleighPhase = 0.75 * (1.0 + fCos*fCos);\r\n"
"  float fMiePhase= 1.5 * ((1.0 - g2) / (2.0 + g2)) * (1.0 + fCos*fCos) / pow(1.0 + g2 - 2.0*g*fCos, 1.5);\r\n"
"  vec4 col=(fRayleighPhase * color0) + (fMiePhase * color1);\r\n"
"  col.a=max(col.b,col.r);\r\n"
"  gl_FragColor = 1 - exp(-fExposure * col);\r\n"
""
"}";

