#include "internalshadermanager.h"
#include "internalterrain.h"
#include "internalshaders.h"

/* Vertex shader */
VECHAR p_ShaderTerrainVertex[] = ""
"uniform vec4 "VE_SHADERPARAM_CAMERAPOS";\r\n"
""
"varying vec3 lightDir;\r\n"
"varying vec3 normal;\r\n"
"varying vec2 texCoord;\r\n"
""
"void main( void )\r\n"
"{\r\n"
"  lightDir = normalize(vec3(gl_LightSource[0].position.xyz) - gl_Vertex.xyz);\r\n"
""
"  normal = normalize(gl_Normal);\r\n"
"  texCoord = gl_MultiTexCoord0.xy;\r\n"
""
"  gl_Position = gl_ModelViewProjectionMatrix * gl_Vertex;\r\n"
"}\r\n";

/* Fragment shader */
VECHAR p_ShaderTerrainFragment[] = ""
"uniform sampler2D "VE_SHADERPARAM_MAP1";\r\n"
"uniform sampler2D "VE_SHADERPARAM_MAP2";\r\n"
"uniform sampler2D "VE_SHADERPARAM_MAP3";\r\n"
"uniform sampler2D "VE_SHADERPARAM_MAP4";\r\n"
"uniform sampler2D "VE_SHADERPARAM_MAPBLEND";\r\n"
""
"uniform vec2 "VE_SHADERPARAM_PARAMETERS";\r\n"
"const int chunkSize = "VE_TERRAIN_CHUNKSIZE_S";\r\n"
""
"varying vec2 texCoord;\r\n"
"varying vec3 lightDir;\r\n"
"varying vec3 normal;\r\n"
""
"void main( void )\r\n"
"{\r\n"
"  vec2 blendTexCoord = vec2(texCoord.x / "VE_SHADERPARAM_PARAMETERS".x, texCoord.y / "VE_SHADERPARAM_PARAMETERS".y);\r\n"
""
"  int chunkX = int(blendTexCoord.x / float(chunkSize));\r\n"
"  int chunkZ = int(blendTexCoord.y / float(chunkSize));\r\n"
""
"  vec2 diffuseTexCoord = vec2(texCoord.x - float(chunkX * (chunkSize-1)), texCoord.y - float(chunkZ * (chunkSize-1)));\r\n"
"  diffuseTexCoord = diffuseTexCoord / float(chunkSize);\r\n"
""
"  vec3 blend = (texture2D("VE_SHADERPARAM_MAPBLEND", blendTexCoord).rgb);\r\n"
""
"  vec4 totalColor = texture2D("VE_SHADERPARAM_MAP1",  diffuseTexCoord) * blend.r +\r\n"
"                    texture2D("VE_SHADERPARAM_MAP2",  diffuseTexCoord) * blend.g +\r\n"
"                    texture2D("VE_SHADERPARAM_MAP3",  diffuseTexCoord) * blend.b;\r\n"
""
"  vec4 diff = gl_LightSource[0].diffuse * max(dot(normal, lightDir), 0.0);\r\n"
"  vec4 light = diff + gl_LightSource[0].ambient;\r\n"
""
"  gl_FragColor = light * totalColor;\r\n"
"}\r\n";
