#include "internalshadermanager.h"
#include "internalshaders.h"

/* Vertex shader */
VECHAR p_ShaderNormalMappingVertex[] = ""
"varying vec3 lightDir;\r\n"
"varying vec3 viewDir;\r\n"
"varying vec2 texCoord;\r\n"
""
"attribute vec4 "VE_SHADERPARAM_TANGENTS";\r\n"
"attribute vec3 "VE_SHADERPARAM_BINORMALS";\r\n"
""
"void main()"
"{"
"  gl_Position = gl_ModelViewProjectionMatrix * gl_Vertex;\r\n"
"  texCoord = gl_MultiTexCoord0.xy;\r\n"
""
"  vec3 vertexPos = vec3(gl_ModelViewMatrix * gl_Vertex);\r\n"
"  vec3 vVertex = vec3(gl_ModelViewMatrix * gl_Vertex);\r\n"
"  vec3 tmpVec = gl_LightSource[0].position.xyz - vVertex;\r\n"
""
"  vec3 n = normalize(gl_NormalMatrix * gl_Normal);\r\n"
"  vec3 t = normalize(gl_NormalMatrix * "VE_SHADERPARAM_TANGENTS".xyz);\r\n"
"  vec3 b = normalize("VE_SHADERPARAM_BINORMALS");\r\n"
""
"  lightDir = vec3(dot(tmpVec, t), dot(tmpVec, b), dot(tmpVec, n));\r\n"
""
"  tmpVec   = -vVertex;\r\n"
"  viewDir  = normalize(vec3(dot(tmpVec, t), dot(tmpVec, b), dot(tmpVec, n)));\r\n"
"}";

/* Fragment shader */
VECHAR p_ShaderNormalMappingFragment[] = ""
"uniform sampler2D "VE_SHADERPARAM_MAPDIFFUSE";\r\n"
"uniform sampler2D "VE_SHADERPARAM_MAPNORMALS";\r\n"
""
"varying vec3 lightDir;\r\n"
"varying vec3 viewDir;\r\n"
"varying vec2 texCoord;\r\n"
""
"void main()"
"{"
"  vec4 baseColor = texture2D("VE_SHADERPARAM_MAPDIFFUSE", texCoord);\r\n"
"  vec3 normal = normalize(texture2D("VE_SHADERPARAM_MAPNORMALS", texCoord).rgb * 2.0 - 1.0);\r\n"
""
"  vec4 ambientColor = gl_LightSource[0].ambient * baseColor;\r\n"
""
"  float diffuse = clamp(dot(lightDir, normal), 0.0, 1.0);\r\n"
"  vec4 diffuseColor = gl_LightSource[0].diffuse * baseColor * diffuse;\r\n;"
""
"  float baseShininess = texture2D("VE_SHADERPARAM_MAPNORMALS", texCoord).a;\r\n"
"  float specular = pow(clamp(dot(reflect(-lightDir, normal), viewDir), 0.0, 1.0), baseShininess);\r\n"
"  vec4 specularColor = gl_LightSource[0].specular * specular;\r\n"
""
"  gl_FragColor = ambientColor + diffuseColor + specularColor;\r\n"
"}";

