#include "internalshadermanager.h"
#include "internalshaders.h"

/* Vertex shader */
VECHAR p_ShaderRenderVertex[] = ""
"varying vec3 lightDir["VE_MAXIMAL_LIGHTS_SHADER"];\r\n"
"varying vec3 viewDir;\r\n"
"varying vec2 texCoord;\r\n"
""
"varying vec3 vertexNormal;\r\n"
"varying vec3 vertexPosition;\r\n"
""
"varying float fogFactor;\r\n"
""
"attribute vec4 "VE_SHADERPARAM_TANGENTS";\r\n"
"attribute vec3 "VE_SHADERPARAM_BINORMALS";\r\n"
""
"uniform int "VE_SHADERPARAM_LIGHTS"["VE_MAXIMAL_LIGHTS_SHADER"];\r\n"
"uniform vec4 "VE_SHADERPARAM_CAMERAPOS";\r\n"
""
""
"  vec3 getLightDirection(int lightID, vec3 t, vec3 b, vec3 n)\r\n"
"  {\r\n"
"    vec3 tmpVec = gl_LightSource[lightID-1].position.xyz - vertexPosition;\r\n"
"    return vec3(dot(tmpVec, t), dot(tmpVec, b), dot(tmpVec, n));\r\n"
"  }\r\n"
""
""
"void main()\r\n"
"{"
"  vertexPosition = vec3(gl_ModelViewMatrix * gl_Vertex);\r\n"
"  vertexNormal   = normalize(gl_NormalMatrix * gl_Normal);\r\n"
""
"  gl_Position = gl_ModelViewProjectionMatrix * gl_Vertex;\r\n"
"  texCoord = gl_MultiTexCoord0.xy;\r\n"
""
"  vec3 t = normalize(gl_NormalMatrix * "VE_SHADERPARAM_TANGENTS".xyz);\r\n"
"  vec3 b = normalize("VE_SHADERPARAM_BINORMALS");\r\n"
""
"  vec3 tmpVec   = -vertexPosition;\r\n"
"  viewDir  = normalize(vec3(dot(tmpVec, t), dot(tmpVec, b), dot(tmpVec, vertexNormal)));\r\n"
""
"  if ("VE_SHADERPARAM_LIGHTS"[1] == 1)\r\n"
"    lightDir[1] = getLightDirection(1, t, b, vertexNormal);\r\n"
"  if ("VE_SHADERPARAM_LIGHTS"[2] == 1)\r\n"
"    lightDir[2] = getLightDirection(2, t, b, vertexNormal);\r\n"
"  if ("VE_SHADERPARAM_LIGHTS"[3] == 1)\r\n"
"    lightDir[3] = getLightDirection(3, t, b, vertexNormal);\r\n"
"  if ("VE_SHADERPARAM_LIGHTS"[4] == 1)\r\n"
"    lightDir[4] = getLightDirection(4, t, b, vertexNormal);\r\n"
"  if ("VE_SHADERPARAM_LIGHTS"[5] == 1)\r\n"
"    lightDir[5] = getLightDirection(5, t, b, vertexNormal);\r\n"
"  if ("VE_SHADERPARAM_LIGHTS"[6] == 1)\r\n"
"    lightDir[6] = getLightDirection(6, t, b, vertexNormal);\r\n"
"  if ("VE_SHADERPARAM_LIGHTS"[7] == 1)\r\n"
"    lightDir[7] = getLightDirection(7, t, b, vertexNormal);\r\n"
"  if ("VE_SHADERPARAM_LIGHTS"[8] == 1)\r\n"
"    lightDir[7] = getLightDirection(8, t, b, vertexNormal);\r\n"
""
"  const float LOG2 = 1.442695;\r\n"
"  float distance = length(gl_Vertex - "VE_SHADERPARAM_CAMERAPOS".xyz);\r\n"
"  fogFactor = exp2(-gl_Fog.density * gl_Fog.density * distance * distance * LOG2);\r\n"
"  fogFactor = clamp(fogFactor, 0.0, 1.0);\r\n"
"}";

/* Fragment shader */
VECHAR p_ShaderRenderFragment[] = ""
"uniform sampler2D "VE_SHADERPARAM_MAPDIFFUSE";\r\n"
"uniform sampler2D "VE_SHADERPARAM_MAPNORMALS";\r\n"
""
"uniform int "VE_SHADERPARAM_LIGHTS"["VE_MAXIMAL_LIGHTS_SHADER"];\r\n"
"uniform int "VE_SHADERPARAM_MAPDIFFUSEFLAG";\r\n"
"uniform int "VE_SHADERPARAM_MAPNORMALSFLAG";\r\n"
""
"varying vec3 vertexNormal;\r\n"
"varying vec3 vertexPosition;\r\n"
""
"  varying float fogFactor;\r\n"
""
"varying vec3 lightDir["VE_MAXIMAL_LIGHTS_SHADER"];\r\n"
"varying vec3 viewDir;\r\n"
"varying vec2 texCoord;\r\n"
""
"vec2 getTCoordinates()\r\n"
"{\r\n"
"  return vec2(texCoord.x, texCoord.y);\r\n"
"}\r\n"
""
"vec4 getDiffuseColor(sampler2D diffuseMap)\r\n"
"{\r\n"
"  return texture2D(diffuseMap, getTCoordinates());\r\n"
"}\r\n"
""
""
"vec3 getNormal(sampler2D normalsMap)\r\n"
"{\r\n"
"  return normalize(texture2D(normalsMap, getTCoordinates()).rgb * 2.0 - 1.0);\r\n"
"}\r\n"
""
""
"vec4 applyNormalMapping(sampler2D diffuseMap, sampler2D normalsMap)\r\n"
"{\r\n"
"  vec4 baseColor      = getDiffuseColor(diffuseMap);\r\n"
"  vec3 normal         = getNormal(normalsMap);\r\n"
"  float baseShininess = texture2D(normalsMap, getTCoordinates()).a;\r\n"
""
"  vec4 ambientColor  = vec4(0.0, 0.0, 0.0, 1.0);\r\n"
"  vec4 diffuseColor  = vec4(0.0, 0.0, 0.0, 1.0);\r\n"
"  vec4 specularColor = vec4(0.0, 0.0, 0.0, 1.0);\r\n"
""
"  for (int lightID = 1; lightID < "VE_MAXIMAL_LIGHTS_SHADER"; lightID++)\r\n"
"    if ("VE_SHADERPARAM_LIGHTS"[lightID] == 1)\r\n"
"    {\r\n"
"      ambientColor += gl_LightSource[lightID-1].ambient * baseColor;\r\n"
""
"      float diffuse = clamp(dot(lightDir[lightID], normal), 0.0, 1.0);\r\n"
"      diffuseColor += gl_LightSource[lightID-1].diffuse * baseColor * diffuse;\r\n;"
""
"      vec3 reflected = -normalize(reflect(lightDir[lightID], normal));\r\n"
"      float specular = pow(clamp(dot(reflected, normal), 0.0, 1.0), baseShininess);\r\n"
"      specularColor += baseColor * gl_LightSource[lightID-1].specular * specular;\r\n"
"    }\r\n"
""
"  return vec4((ambientColor + diffuseColor + specularColor).rgb, baseColor.a);\r\n"
"}\r\n"

"vec4 applyTextureMapping(sampler2D diffuseMap)\r\n"
"{\r\n"
"  vec4 baseColor = getDiffuseColor(diffuseMap);\r\n"
"  vec3 E = normalize(-vertexPosition);\r\n"
""
"  vec4 ambientColor  = vec4(0.0, 0.0, 0.0, 1.0);\r\n"
"  vec4 diffuseColor  = baseColor;\r\n"
""
"  for (int lightID = 1; lightID < "VE_MAXIMAL_LIGHTS_SHADER"; lightID++)\r\n"
"    if ("VE_SHADERPARAM_LIGHTS"[lightID] == 1)\r\n"
"    {\r\n"
"      vec3 L = normalize(gl_LightSource[lightID-1].position.xyz - vertexPosition);\r\n"
"      vec3 R = normalize(-reflect(L, vertexNormal));\r\n"
""
"      ambientColor += gl_LightSource[lightID-1].ambient * baseColor;\r\n"
""
"      vec4 currentDiffuse = gl_FrontLightProduct[lightID-1].diffuse * max(dot(vertexNormal, L), 0.0);\r\n"
"      diffuseColor       += clamp(currentDiffuse, 0.0, 1.0);\r\n"
"    }\r\n"
""
"  return vec4((ambientColor + diffuseColor).rgb, baseColor.a);\r\n"
"}\r\n"
""
""
"vec4 applySimpleLightingModel()\r\n"
"{\r\n"
"  vec3 E = normalize(-vertexPosition);\r\n"
""
"  vec4 ambientColor  = vec4(0.0, 0.0, 0.0, 1.0);\r\n"
"  vec4 diffuseColor  = vec4(0.0, 0.0, 0.0, 1.0);\r\n"
""
"  for (int lightID = 1; lightID < "VE_MAXIMAL_LIGHTS_SHADER"; lightID++)\r\n"
"    if ("VE_SHADERPARAM_LIGHTS"[lightID] == 1)\r\n"
"    {\r\n"
"      vec3 L = normalize(gl_LightSource[lightID-1].position.xyz - vertexPosition);\r\n"
"      vec3 R = normalize(-reflect(L, vertexNormal));\r\n"
""
"      ambientColor += gl_LightSource[lightID-1].ambient;\r\n"
""
"      vec4 currentDiffuse = gl_FrontLightProduct[lightID-1].diffuse * max(dot(vertexNormal, L), 0.0);\r\n"
"      diffuseColor += clamp(currentDiffuse, 0.0, 1.0);\r\n"
"    }\r\n"
""
"  return ambientColor + diffuseColor;\r\n"
"}\r\n"
""
""
"void main()"
"{"
"  bool renderedFlag = false;\r\n"
"  vec4 realObjectColor = vec4(0.0, 1.0, 0.0, 1.0);\r\n"
""
"  if (("VE_SHADERPARAM_MAPNORMALSFLAG" == 1)&&("VE_SHADERPARAM_MAPDIFFUSEFLAG" == 1))\r\n"
"  {\r\n"
"    realObjectColor = applyNormalMapping("VE_SHADERPARAM_MAPDIFFUSE", "VE_SHADERPARAM_MAPNORMALS");\r\n"
"    renderedFlag = true;\r\n"
"  }\r\n"
""
"  if ((!renderedFlag)&&("VE_SHADERPARAM_MAPDIFFUSEFLAG" == 1))\r\n"
"  {\r\n"
"    realObjectColor = applyTextureMapping("VE_SHADERPARAM_MAPDIFFUSE");\r\n"
"    renderedFlag = true;\r\n"
"  }\r\n"

"  if (!renderedFlag)\r\n"
"  {\r\n"
"    realObjectColor = applySimpleLightingModel();\r\n"
"    renderedFlag = true;\r\n"
"  }\r\n"
""
"  gl_FragColor = vec4(mix(gl_Fog.color, realObjectColor, fogFactor).rgb, realObjectColor.a);\r\n"
"}";

