#include "internalshadermanager.h"
#include "internalshaders.h"

/* Vertex shader */
VECHAR p_ShaderCartoonVertex[] = ""
"varying vec3 vNormal;\r\n"
"varying vec3 vVertex;\r\n"
""
"void main(void)\r\n"
"{\r\n"
"  vVertex = gl_Vertex.xyz;\r\n"
"  vNormal = gl_Normal;\r\n"
"  gl_Position = gl_ModelViewProjectionMatrix * gl_Vertex;\r\n"
"}\r\n";

/* Fragment shader */
VECHAR p_ShaderCartoonFragment[] = ""
"varying vec3 vNormal;\r\n"
"varying vec3 vVertex;\r\n"
""
"uniform vec4 "VE_SHADERPARAM_CAMERAPOS";\r\n"
""
"#define shininess 20.0\r\n"
""
"void main(void)\r\n"
"{\r\n"
"  vec4 color0 = vec4(0.8, 0.0, 0.0, 1.0); // Material Color\r\n"
"  vec4 color1 = vec4(0.0, 0.0, 0.0, 1.0); // Silhouette Color\r\n"
"  vec4 color2 = vec4(0.8, 0.0, 0.0, 1.0); // Specular Color\r\n"
""
"  vec3 eyePos = "VE_SHADERPARAM_CAMERAPOS".xyz;\r\n"
"  vec3 lightPos = gl_LightSource[0].position.xyz;\r\n"
""
"  vec3 Normal = normalize(gl_NormalMatrix * vNormal);\r\n"
"  vec3 EyeVert = normalize(eyePos - vVertex);\r\n"
"  vec3 LightVert = normalize(lightPos - vVertex);\r\n"
"  vec3 EyeLight = normalize(LightVert+EyeVert);\r\n"
""
"  float sil = max(dot(Normal,EyeVert), 0.0);\r\n"
"  if (sil < 0.3)\r\n"
"    gl_FragColor = color1;\r\n"
"  else\r\n"
"  {\r\n"
"    gl_FragColor = color0;\r\n"
"    float spec = pow(max(dot(Normal,EyeLight),0.0), shininess); // Specular part\r\n"
"    if (spec < 0.2)\r\n"
"      gl_FragColor *= 0.8;\r\n"
"    else \r\n"
"      gl_FragColor = color2;\r\n"
""
"    float diffuse = max(dot(Normal,LightVert), 0.0);\r\n"
"    if (diffuse < 0.5)\r\n"
"      gl_FragColor *=0.8;\r\n"
"  }\r\n"
"}\r\n";

