name: Release

permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 22
          cache: maven
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
          server-id: central
          server-username: ${{ secrets.CENTRAL_TOKEN_USERNAME }}
          server-password: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}

      - name: Build & publish
        run: mvn --batch-mode -P release -Dgpg.passphrase="${{ secrets.GPG_PASSPHRASE }}" clean deploy -pl container,engine | tee maven-build.log

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: maven-logs
          path: maven-build.log